---
title: "differential expression analysis"
author: "Manuel Cortes"
date: "2023-09-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Attach the DESeq2 library
library(DESeq2)

# Attach the ggplot2 library for plotting
library(ggplot2)

# We will need this so we can use the pipe: %>%
library(magrittr)

# Human Annotation
library(org.Hs.eg.db)

set.seed(12345)
```

# Analysis

# For DESeq, please see differential-expression-analysis.Rmd.
# Here, we will simply load the result from it

# Heatmap

```{r}
library(devtools)
library(ComplexHeatmap)
library(circlize)

```


```{r}

# Define the file path
file_path <- file.path("results", "SRP076307_diff_expr_results.tsv")

# Read the file
deseq_df <- readr::read_tsv(file_path)

# Filter for significantly differentially expressed genes using the threshold column
sig_genes_df <- deseq_df %>%
  dplyr::filter(threshold == TRUE)
sig_genes_list <- sig_genes_df$Gene

filtered_gene_matrix <- gene_matrix[rownames(gene_matrix) %in% sig_genes_list, ]

# Scale the Data
scaled_filtered_gene_matrix <- t(apply(filtered_gene_matrix, 1, scale))

class(scaled_filtered_gene_matrix)  # Should return "matrix"
dim(scaled_filtered_gene_matrix)    # Should return the dimensions of the matrix, i.e., number of rows (genes) and columns (samples)


Heatmap(scaled_filtered_gene_matrix,
        name = "z-score",
        show_row_names = FALSE,
        show_column_names = FALSE,
        cluster_rows = TRUE,
        cluster_columns = TRUE,
        col = colorRamp2(c(-2, 0, 2), c("blue", "white", "red")))

```

